os: linux
arch:
  - arm64
dist: buster
language:
  - python
cache: pip
python: "3.7.3"
install:
  # Needed for the libgfortran5 package.
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get update
  # Sktree Balltree
  - sudo apt-get install gfortran
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libblas-dev
  - sudo apt-get install libgfortran5
  - sudo apt-get install liblapack-dev
  # Python libaries
  - sudo apt-get install python3-pip
  - pip3 install -r requirements.txt
  # LabJack
  - sudo apt-get install libusb-1.0-0-dev
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  # Pytest doesn't play well with absl.
  - python3 /home/travis/build/djhedges/exit_speed/accelerometer_test.py
  - python3 /home/travis/build/djhedges/exit_speed/data_logger_test.py
  - python3 /home/travis/build/djhedges/exit_speed/exit_speed_test.py
  - python3 /home/travis/build/djhedges/exit_speed/labjack_test.py
  - python3 /home/travis/build/djhedges/exit_speed/lap_lib_test.py
  - python3 /home/travis/build/djhedges/exit_speed/leds_test.py
  - python3 /home/travis/build/djhedges/exit_speed/timescale_test.py
  - python3 /home/travis/build/djhedges/exit_speed/wbo2_test.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py --keep-going -o /tmp
  - pylint --ignore-patterns=.*pb2.* *.py
