language: python
python:
  - "3.7"
before install:
  - sudo apt-get install python3-protobuf
install:
  - protoc -I ./ --python_out ./ gps.proto
  - pip3 install -r requirements.txt
script:
  - pytest
