arch:
  - arm64
dist: buster
language: python
cache: pip
python:
  - "3.7"
before install:
  - pip3 install --upgrade pip
install:
  - sudo apt-get install libblas3 liblapack3 libusb-1.0-0-dev python3-sklearn
  - pip3 install -r requirements.txt
  - git clone https://github.com/labjack/exodriver.git
before script:
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/djhedges/exit_speed/*.py
