os: linux
arch: arm64
dist: buster
language: python
cache: pip
python: "3.7.3"
install:
  # Needed for the libgfortran5 package.
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get update
  - pip3 install -r requirements.txt
  # Sktree Balltree
  - sudo apt-get install gfortran
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libblas-dev
  - sudo apt-get install libgfortran5
  - sudo apt-get install liblapack-dev
  - sudo apt install g++ unzip zip
  - mkdir /tmp/bin
  # Bazel for Tensorflow compiling.
  - git clone https://github.com/bazelbuild/bazel.git
  - cd bazel
  - git checkout 0.26.1
  - ./compile.sh
  - PATH=$PATH:$(pwd)/output/bazel
  # Tensorflow
  - git clone https://github.com/tensorflow/tensorflow.git
  - cd tensorflow
  - git checkout r1.15
  - ./configure
  - bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package
  - ls /tmp/tensorflow_pkg/
  - pip3 install /tmp/tensorflow_pkg/tensorflow-1.14.0.whl
  - cd -
  # LabJack
  - sudo apt-get install libusb-1.0-0-dev
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --disable-pytest-warnings
  - pytype /home/travis/build/djhedges/exit_speed/*.py -o /tmp/pytype
