arch:
  - arm64
dist: buster
language: python
python:
  - "3.7"
before install:
   - sudo apt-get install autoconf automake libtool curl make g++ wget unzip
   - git clone https://github.com/protocolbuffers/protobuf.git
   - cd protobuf/
   - git submodule update --init --recursive
   - ./autogen.sh
   - ./configure
   - make
   - make check
   - sudo make install
   - sudo ldconfig
install:
  - /usr/local/bin/protoc -I ./ --python_out ./ gps.proto
  - pip3 install -r requirements.txt
script:
  - pytest
