arch:
  - arm64
dist: buster
language: python
python:
  - "3.7"
before install:
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get -q update
  - sudo apt-get -y install python3-protobuf
install:
  - protoc -I ./ --python_out ./ gps.proto
  - pip3 install -r requirements.txt
script:
  - pytest
