os: linux
arch: arm64
dist: buster
language: python
cache: pip
python: "3.7.3"
install:
  # Needed for the libgfortran5 package.
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get update
  - pip3 install -r requirements.txt
  # Sktree Balltree
  - sudo apt-get install gfortran
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libblas-dev
  - sudo apt-get install libgfortran5
  - sudo apt-get install liblapack-dev
  - sudo apt install g++ unzip zip
  # Tensorflow
  - mkdir bin
  - wget https://github.com/bazelbuild/bazel/releases/download/3.5.0/bazel-3.5.0-linux-arm64 bin/bazel
  - chmod +x bin/bazel
  - PATH=$PATH:bin/
  - echo $PATH
  - pwd
  - git clone https://github.com/tensorflow/tensorflow.git
  - cd tensorflow
  - git checkout r1.14
  - ./configure
  - bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package
  - ls /tmp/tensorflow_pkg/
  - pip3 install /tmp/tensorflow_pkg/tensorflow-1.14.0.whl
  - cd -
  # LabJack
  - sudo apt-get install libusb-1.0-0-dev
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/build/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py -o /tmp/pytype
