arch:
  - arm64
dist: buster
language: python
cache: pip
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
before script:
  - bin/protoc-3.11.2 -I ./ --python_out ./ gps.proto
script:
  - pytest
