os: linux
arch:
  - arm64
dist: buster
language:
  - python
cache: pip
python:
  - "3.7.3"
install:
  - sudo apt-get update
  - sudo apt-get install python3-numpy
  - sudo apt-get install python3-pandas
  - sudo apt-get install python-mock
  - sudo apt-get install python-serial
  # Needed for the libgfortran5 package.
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9165938D90FDDD2E
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get update
  - sudo apt-get install fonts-liberation
  # Sktree Balltree
  - sudo apt-get install gfortran
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libblas-dev
  - sudo apt-get install libgfortran5
  - sudo apt-get install liblapack-dev
  # Python libaries
  - sudo apt-get install python3-pip
  - pip3 install -r requirements.txt
  # LabJack
  - sudo apt-get install libusb-1.0-0-dev
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  # Pytest doesn't play well with absl.
  - cd /home/travis/build/djhedges/exit_speed
  - python3 -m exit_speed.accelerometer_test
  - python3 -m exit_speed.common_lib_test
  - python3 -m exit_speed.data_logger_test
  - python3 -m exit_speed.gyroscope_test
  - python3 -m exit_speed.import_data_test
  - python3 -m exit_speed.labjack_test
  - python3 -m exit_speed.lap_lib_test
  - python3 -m exit_speed.leds_test
  - python3 -m exit_speed.main_test
  - python3 -m exit_speed.postgres_test
  - python3 -m exit_speed.sensor_test
  - python3 -m exit_speed.tire_temperature_test
  - python3 -m exit_speed.tracks_test
  - python3 -m exit_speed.wbo2_test
