arch:
  - arm64
dist: buster
language: python
python:
  - "3.7"
install:
  - sudo apt-get install protobuf-compiler
  - pip3 install -r requirements.txt
before script:
  - protoc -I ./ --python_out ./ gps.proto
script:
  - pytest
