arch:
  - arm64
dist: buster
language: python
cache: pip
python:
  - "3.7"
install:
  - sudo apt-get install libusb-1.0-0-dev
  - pip3 install -r requirements.txt
  - git clone https://github.com/labjack/exodriver.git
before script:
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=djhedges/exit_speed/gps_pb2.py
  - pytype djhedges/exit_speed/*.py
