os: linux
arch: arm64
dist: buster
language: python
cache:
  - apt
  - pip
python: "3.7.3"
install:
  - sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 9165938D90FDDD2E
  - sudo add-apt-repository -y 'deb [arch=armhf] http://raspbian.raspberrypi.org/raspbian buster main'
  - sudo apt-get update
  - pip3 install -r requirements.txt
  # Sktree Balltree
  - sudo apt install libatlas3-base libgfortran5
  - pip3 install scipy==1.4.1 --index-url https://www.piwheels.org/simple --platform linux/arm/v7 --no-deps
  - pip3 install scikit-learn==0.20.2 --index-url https://www.piwheels.org/simple --platform linux/arm/v7 --no-deps
  # LabJack
  - sudo apt-get install libusb-1.0-0-dev
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/build/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py
