arch:
  - arm64
dist: buster
language: python
python:
  - "3.7"
install:
  - sudo apt-get install autoconf automake libtool curl make g++ wget unzip
  - pip3 install -r requirements.txt
after install:
script:
  - bash compile_protobuf.sh
  - pytest
