arch:
  - arm64
dist: buster
language: python
cache: pip
python:
  # _with_ Used to get scikit working.
  - "3.7__with_system_site_packages"
install:
  - sudo apt-get install libgfortran5 libblas3 liblapack3 liblapack-dev libblas-dev libatlas-base-dev libusb-1.0-0-dev python3-sklearn python3-sklearn-lib python3-nose python3-pytest python3-matplotlib
  - pip3 install -r requirements.txt
  - git clone https://github.com/labjack/exodriver.git
before script:
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/build/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py
