arch:
  - arm64
dist: buster
language: python
cache: pip
python:
  - "3.7"
install:
  - sudo apt-get install libusb-1.0-0
  - pip3 install -r requirements.txt
  - git clone https://github.com/labjack/exodriver.git
  - cd exodriver
  - sudo ./install.sh
script:
  - pytest
