arch:
  - arm64
dist: buster
language: python
cache:
  - apt
  - pip
python:
  - "3.7.3"
install:
  - sudo apt-get install gfortran libgfortran5 libblas3 liblapack3 liblapack-dev libblas-dev libatlas-base-dev libusb-1.0-0-dev
  - pip3 install -r requirements.txt
  - git clone https://github.com/labjack/exodriver.git
  - pip3 install --only-binary scipy==1.4.1
  - pip3 install --only-binary scikit-learn==0.20.2
before script:
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/build/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py
