os: linux
arch:
  - arm64
dist: buster
language: python
cache:
  - apt
  - pip
python:
  - "3.7.3"
before install:
  - sudo apt-get install gfortran
  - sudo apt-get install libgfortran5
  - sudo apt-get install libblas3
  - sudo apt-get install liblapack3
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libblas-dev
  - sudo apt-get install libatlas-base-dev
  - sudo apt-get install libusb-1.0-0-dev
  - pip3 install --upgrade pip
install:
  - pip3 install -r requirements.txt
  - pip3 install --only-binary:all scipy==1.4.1
  - pip3 install --only-binary:all scikit-learn==0.20.2
  - git clone https://github.com/labjack/exodriver.git
before script:
  - cd exodriver
  - sudo ./install.sh
  - cd -
script:
  - pytest --ignore=/home/travis/build/djhedges/exit_speed/gps_pb2.py
  - pytype /home/travis/build/djhedges/exit_speed/*.py
