//!/usr/bin/python3
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// sudo apt install python3-protobuf
// Compile with protoc -I ./ --go_out=./ --go_opt=paths=source_relative --python_out ./ gps.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.2
// source: gps.proto

package gps_go_proto

import (
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat                 float64              `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                 float64              `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt                 float64              `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed               float64              `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"` // meters/second
	Time                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	StartFinishDistance float64              `protobuf:"fixed64,6,opt,name=start_finish_distance,json=startFinishDistance,proto3" json:"start_finish_distance,omitempty"` // Distance to the start/finish.
	TpsVoltage          float64              `protobuf:"fixed64,7,opt,name=tps_voltage,json=tpsVoltage,proto3" json:"tps_voltage,omitempty"`                              // Throttle position sensor voltage.
	WaterTempVoltage    float64              `protobuf:"fixed64,8,opt,name=water_temp_voltage,json=waterTempVoltage,proto3" json:"water_temp_voltage,omitempty"`
	OilPressureVoltage  float64              `protobuf:"fixed64,9,opt,name=oil_pressure_voltage,json=oilPressureVoltage,proto3" json:"oil_pressure_voltage,omitempty"`
	Rpm                 float64              `protobuf:"fixed64,10,opt,name=rpm,proto3" json:"rpm,omitempty"`
	Afr                 float64              `protobuf:"fixed64,11,opt,name=afr,proto3" json:"afr,omitempty"`                                                     // Air fuel ratio.
	FuelLevelVoltage    float64              `protobuf:"fixed64,12,opt,name=fuel_level_voltage,json=fuelLevelVoltage,proto3" json:"fuel_level_voltage,omitempty"` // Air fuel ratio.
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_gps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_gps_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Point) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Point) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Point) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Point) GetStartFinishDistance() float64 {
	if x != nil {
		return x.StartFinishDistance
	}
	return 0
}

func (x *Point) GetTpsVoltage() float64 {
	if x != nil {
		return x.TpsVoltage
	}
	return 0
}

func (x *Point) GetWaterTempVoltage() float64 {
	if x != nil {
		return x.WaterTempVoltage
	}
	return 0
}

func (x *Point) GetOilPressureVoltage() float64 {
	if x != nil {
		return x.OilPressureVoltage
	}
	return 0
}

func (x *Point) GetRpm() float64 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *Point) GetAfr() float64 {
	if x != nil {
		return x.Afr
	}
	return 0
}

func (x *Point) GetFuelLevelVoltage() float64 {
	if x != nil {
		return x.FuelLevelVoltage
	}
	return 0
}

type Lap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points   []*Point           `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Duration *duration.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"` // Time it took to finish the lap.
	Number   int32              `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Lap) Reset() {
	*x = Lap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lap) ProtoMessage() {}

func (x *Lap) ProtoReflect() protoreflect.Message {
	mi := &file_gps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lap.ProtoReflect.Descriptor instead.
func (*Lap) Descriptor() ([]byte, []int) {
	return file_gps_proto_rawDescGZIP(), []int{1}
}

func (x *Lap) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Lap) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Lap) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Laps        []*Lap `protobuf:"bytes,1,rep,name=laps,proto3" json:"laps,omitempty"`
	Track       string `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`
	StartFinish *Point `protobuf:"bytes,3,opt,name=start_finish,json=startFinish,proto3" json:"start_finish,omitempty"` // Location of start/finish.
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_gps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_gps_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetLaps() []*Lap {
	if x != nil {
		return x.Laps
	}
	return nil
}

func (x *Session) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *Session) GetStartFinish() *Point {
	if x != nil {
		return x.StartFinish
	}
	return nil
}

var File_gps_proto protoreflect.FileDescriptor

var file_gps_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x70, 0x73,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8a, 0x03, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x6c,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x73, 0x74, 0x61, 0x72, 0x74, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x70, 0x73, 0x5f, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x74, 0x70, 0x73, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x12,
	0x77, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x76, 0x6f, 0x6c, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x77, 0x61, 0x74, 0x65, 0x72, 0x54,
	0x65, 0x6d, 0x70, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x6f, 0x69,
	0x6c, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x5f, 0x76, 0x6f, 0x6c, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x6f, 0x69, 0x6c, 0x50, 0x72, 0x65,
	0x73, 0x73, 0x75, 0x72, 0x65, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x70, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x72, 0x70, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x66, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x66, 0x72,
	0x12, 0x2c, 0x0a, 0x12, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x76,
	0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x66, 0x75,
	0x65, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x22, 0x78,
	0x0a, 0x03, 0x4c, 0x61, 0x70, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x70, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x6c, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x67, 0x70, 0x73, 0x2e, 0x4c, 0x61, 0x70, 0x52, 0x04, 0x6c, 0x61, 0x70,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x67, 0x70, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x68, 0x65, 0x64, 0x67, 0x65, 0x73, 0x2f, 0x65, 0x78,
	0x69, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x2f, 0x67, 0x70, 0x73, 0x5f, 0x67, 0x6f, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gps_proto_rawDescOnce sync.Once
	file_gps_proto_rawDescData = file_gps_proto_rawDesc
)

func file_gps_proto_rawDescGZIP() []byte {
	file_gps_proto_rawDescOnce.Do(func() {
		file_gps_proto_rawDescData = protoimpl.X.CompressGZIP(file_gps_proto_rawDescData)
	})
	return file_gps_proto_rawDescData
}

var file_gps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gps_proto_goTypes = []interface{}{
	(*Point)(nil),               // 0: gps.Point
	(*Lap)(nil),                 // 1: gps.Lap
	(*Session)(nil),             // 2: gps.Session
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*duration.Duration)(nil),   // 4: google.protobuf.Duration
}
var file_gps_proto_depIdxs = []int32{
	3, // 0: gps.Point.time:type_name -> google.protobuf.Timestamp
	0, // 1: gps.Lap.points:type_name -> gps.Point
	4, // 2: gps.Lap.duration:type_name -> google.protobuf.Duration
	1, // 3: gps.Session.laps:type_name -> gps.Lap
	0, // 4: gps.Session.start_finish:type_name -> gps.Point
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gps_proto_init() }
func file_gps_proto_init() {
	if File_gps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gps_proto_goTypes,
		DependencyIndexes: file_gps_proto_depIdxs,
		MessageInfos:      file_gps_proto_msgTypes,
	}.Build()
	File_gps_proto = out.File
	file_gps_proto_rawDesc = nil
	file_gps_proto_goTypes = nil
	file_gps_proto_depIdxs = nil
}
