# pytype: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gps_pb2 as gps__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='reflector.proto',
  package='reflector',
  syntax='proto3',
  serialized_options=_b('Z1github.com/djhedges/exit_speed/reflector_go_proto'),
  serialized_pb=_b('\n\x0freflector.proto\x12\treflector\x1a\tgps.proto\x1a\x1egoogle/protobuf/duration.proto\"i\n\x0bPointUpdate\x12\x19\n\x05point\x18\x01 \x01(\x0b\x32\n.gps.Point\x12\x0e\n\x06lap_id\x18\x02 \x01(\x05\x12\x12\n\nsession_id\x18\x03 \x01(\x05\x12\x1b\n\x13\x65lapsed_duration_ms\x18\x04 \x01(\x05\"\x1f\n\tLapNumber\x12\x12\n\nlap_number\x18\x01 \x01(\x05\":\n\x0bLapDuration\x12+\n\x08\x64uration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\"\n\n\x08Response2\xc2\x01\n\x07Reflect\x12<\n\x0b\x45xportPoint\x12\x16.reflector.PointUpdate\x1a\x13.reflector.Response\"\x00\x12\x35\n\x06NewLap\x12\x14.reflector.LapNumber\x1a\x13.reflector.Response\"\x00\x12\x42\n\x11UpdateLapDuration\x12\x16.reflector.LapDuration\x1a\x13.reflector.Response\"\x00\x42\x33Z1github.com/djhedges/exit_speed/reflector_go_protob\x06proto3')
  ,
  dependencies=[gps__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_POINTUPDATE = _descriptor.Descriptor(
  name='PointUpdate',
  full_name='reflector.PointUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='reflector.PointUpdate.point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lap_id', full_name='reflector.PointUpdate.lap_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='reflector.PointUpdate.session_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsed_duration_ms', full_name='reflector.PointUpdate.elapsed_duration_ms', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=178,
)


_LAPNUMBER = _descriptor.Descriptor(
  name='LapNumber',
  full_name='reflector.LapNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lap_number', full_name='reflector.LapNumber.lap_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=211,
)


_LAPDURATION = _descriptor.Descriptor(
  name='LapDuration',
  full_name='reflector.LapDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='reflector.LapDuration.duration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=271,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='reflector.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=283,
)

_POINTUPDATE.fields_by_name['point'].message_type = gps__pb2._POINT
_LAPDURATION.fields_by_name['duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['PointUpdate'] = _POINTUPDATE
DESCRIPTOR.message_types_by_name['LapNumber'] = _LAPNUMBER
DESCRIPTOR.message_types_by_name['LapDuration'] = _LAPDURATION
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointUpdate = _reflection.GeneratedProtocolMessageType('PointUpdate', (_message.Message,), dict(
  DESCRIPTOR = _POINTUPDATE,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.PointUpdate)
  ))
_sym_db.RegisterMessage(PointUpdate)

LapNumber = _reflection.GeneratedProtocolMessageType('LapNumber', (_message.Message,), dict(
  DESCRIPTOR = _LAPNUMBER,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.LapNumber)
  ))
_sym_db.RegisterMessage(LapNumber)

LapDuration = _reflection.GeneratedProtocolMessageType('LapDuration', (_message.Message,), dict(
  DESCRIPTOR = _LAPDURATION,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.LapDuration)
  ))
_sym_db.RegisterMessage(LapDuration)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_REFLECT = _descriptor.ServiceDescriptor(
  name='Reflect',
  full_name='reflector.Reflect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=286,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExportPoint',
    full_name='reflector.Reflect.ExportPoint',
    index=0,
    containing_service=None,
    input_type=_POINTUPDATE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NewLap',
    full_name='reflector.Reflect.NewLap',
    index=1,
    containing_service=None,
    input_type=_LAPNUMBER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLapDuration',
    full_name='reflector.Reflect.UpdateLapDuration',
    index=2,
    containing_service=None,
    input_type=_LAPDURATION,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REFLECT)

DESCRIPTOR.services_by_name['Reflect'] = _REFLECT

# @@protoc_insertion_point(module_scope)
