# pytype: skip-file
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import reflector_pb2 as reflector__pb2


class ReflectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExportPoint = channel.unary_unary(
        '/reflector.Reflect/ExportPoint',
        request_serializer=reflector__pb2.PointUpdate.SerializeToString,
        response_deserializer=reflector__pb2.Response.FromString,
        )
    self.NewLap = channel.unary_unary(
        '/reflector.Reflect/NewLap',
        request_serializer=reflector__pb2.LapNumber.SerializeToString,
        response_deserializer=reflector__pb2.Response.FromString,
        )
    self.UpdateLapDuration = channel.unary_unary(
        '/reflector.Reflect/UpdateLapDuration',
        request_serializer=reflector__pb2.LapDuration.SerializeToString,
        response_deserializer=reflector__pb2.Response.FromString,
        )


class ReflectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExportPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewLap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateLapDuration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReflectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExportPoint': grpc.unary_unary_rpc_method_handler(
          servicer.ExportPoint,
          request_deserializer=reflector__pb2.PointUpdate.FromString,
          response_serializer=reflector__pb2.Response.SerializeToString,
      ),
      'NewLap': grpc.unary_unary_rpc_method_handler(
          servicer.NewLap,
          request_deserializer=reflector__pb2.LapNumber.FromString,
          response_serializer=reflector__pb2.Response.SerializeToString,
      ),
      'UpdateLapDuration': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateLapDuration,
          request_deserializer=reflector__pb2.LapDuration.FromString,
          response_serializer=reflector__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'reflector.Reflect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
