# pytype: skip-file
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gps_pb2 as gps__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='reflector.proto',
  package='reflector',
  syntax='proto3',
  serialized_options=b'Z8github.com/djhedges/exit_speed/protos/reflector_go_proto',
  serialized_pb=b'\n\x0freflector.proto\x12\treflector\x1a\tgps.proto\x1a\x1egoogle/protobuf/duration.proto\"<\n\x0bPointUpdate\x12\x19\n\x05point\x18\x01 \x01(\x0b\x32\n.gps.Point\x12\x12\n\nlap_number\x18\x02 \x01(\x05\"\x1c\n\x06NewLap\x12\x12\n\nlap_number\x18\x02 \x01(\x05\"@\n\x11UpdateLapDuration\x12+\n\x08\x64uration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationB:Z8github.com/djhedges/exit_speed/protos/reflector_go_protob\x06proto3'
  ,
  dependencies=[gps__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_POINTUPDATE = _descriptor.Descriptor(
  name='PointUpdate',
  full_name='reflector.PointUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='reflector.PointUpdate.point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lap_number', full_name='reflector.PointUpdate.lap_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=133,
)


_NEWLAP = _descriptor.Descriptor(
  name='NewLap',
  full_name='reflector.NewLap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lap_number', full_name='reflector.NewLap.lap_number', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=163,
)


_UPDATELAPDURATION = _descriptor.Descriptor(
  name='UpdateLapDuration',
  full_name='reflector.UpdateLapDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='reflector.UpdateLapDuration.duration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=229,
)

_POINTUPDATE.fields_by_name['point'].message_type = gps__pb2._POINT
_UPDATELAPDURATION.fields_by_name['duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['PointUpdate'] = _POINTUPDATE
DESCRIPTOR.message_types_by_name['NewLap'] = _NEWLAP
DESCRIPTOR.message_types_by_name['UpdateLapDuration'] = _UPDATELAPDURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointUpdate = _reflection.GeneratedProtocolMessageType('PointUpdate', (_message.Message,), {
  'DESCRIPTOR' : _POINTUPDATE,
  '__module__' : 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.PointUpdate)
  })
_sym_db.RegisterMessage(PointUpdate)

NewLap = _reflection.GeneratedProtocolMessageType('NewLap', (_message.Message,), {
  'DESCRIPTOR' : _NEWLAP,
  '__module__' : 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.NewLap)
  })
_sym_db.RegisterMessage(NewLap)

UpdateLapDuration = _reflection.GeneratedProtocolMessageType('UpdateLapDuration', (_message.Message,), {
  'DESCRIPTOR' : _UPDATELAPDURATION,
  '__module__' : 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:reflector.UpdateLapDuration)
  })
_sym_db.RegisterMessage(UpdateLapDuration)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
