// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Compile with:
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
// LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3 -m grpc_tools.protoc -I ./ --go_out=./reflector_go_proto --go-grpc_out=./reflector_go_proto --go_opt=paths=source_relative --python_out ./ --grpc_python_out ./ reflector.proto
// Not sure why but something is still screwy with the grpc output path.
// Why not one more hack?
// mv reflector_go_proto/github.com/djhedges/exit_speed/reflector_go_proto/reflector_grpc.pb.go reflector_go_proto/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: reflector.proto

package reflector_go_proto

import (
	gps_go_proto "github.com/djhedges/exit_speed/gps_go_proto"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PointUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point             *gps_go_proto.Point `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	LapId             int32               `protobuf:"varint,2,opt,name=lap_id,json=lapId,proto3" json:"lap_id,omitempty"`
	SessionId         int32               `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ElapsedDurationMs int32               `protobuf:"varint,4,opt,name=elapsed_duration_ms,json=elapsedDurationMs,proto3" json:"elapsed_duration_ms,omitempty"`
}

func (x *PointUpdate) Reset() {
	*x = PointUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reflector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointUpdate) ProtoMessage() {}

func (x *PointUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_reflector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointUpdate.ProtoReflect.Descriptor instead.
func (*PointUpdate) Descriptor() ([]byte, []int) {
	return file_reflector_proto_rawDescGZIP(), []int{0}
}

func (x *PointUpdate) GetPoint() *gps_go_proto.Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *PointUpdate) GetLapId() int32 {
	if x != nil {
		return x.LapId
	}
	return 0
}

func (x *PointUpdate) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PointUpdate) GetElapsedDurationMs() int32 {
	if x != nil {
		return x.ElapsedDurationMs
	}
	return 0
}

type LapNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LapNumber int32 `protobuf:"varint,1,opt,name=lap_number,json=lapNumber,proto3" json:"lap_number,omitempty"`
}

func (x *LapNumber) Reset() {
	*x = LapNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reflector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LapNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LapNumber) ProtoMessage() {}

func (x *LapNumber) ProtoReflect() protoreflect.Message {
	mi := &file_reflector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LapNumber.ProtoReflect.Descriptor instead.
func (*LapNumber) Descriptor() ([]byte, []int) {
	return file_reflector_proto_rawDescGZIP(), []int{1}
}

func (x *LapNumber) GetLapNumber() int32 {
	if x != nil {
		return x.LapNumber
	}
	return 0
}

type LapDuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"` // Time it took to finish the lap.
}

func (x *LapDuration) Reset() {
	*x = LapDuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reflector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LapDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LapDuration) ProtoMessage() {}

func (x *LapDuration) ProtoReflect() protoreflect.Message {
	mi := &file_reflector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LapDuration.ProtoReflect.Descriptor instead.
func (*LapDuration) Descriptor() ([]byte, []int) {
	return file_reflector_proto_rawDescGZIP(), []int{2}
}

func (x *LapDuration) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reflector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_reflector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_reflector_proto_rawDescGZIP(), []int{3}
}

var File_reflector_proto protoreflect.FileDescriptor

var file_reflector_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x09, 0x67, 0x70,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x70, 0x73, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x61, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x61, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x2e, 0x0a, 0x13, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x65, 0x6c,
	0x61, 0x70, 0x73, 0x65, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22,
	0x2a, 0x0a, 0x09, 0x4c, 0x61, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x61, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6c, 0x61, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0b, 0x4c,
	0x61, 0x70, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc2, 0x01,
	0x0a, 0x07, 0x52, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x72, 0x65, 0x66, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x1a, 0x13, 0x2e, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x4c, 0x61,
	0x70, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x61,
	0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x70, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x4c, 0x61, 0x70, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x72, 0x65,
	0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x6a, 0x68, 0x65, 0x64, 0x67, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x2f, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x67,
	0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reflector_proto_rawDescOnce sync.Once
	file_reflector_proto_rawDescData = file_reflector_proto_rawDesc
)

func file_reflector_proto_rawDescGZIP() []byte {
	file_reflector_proto_rawDescOnce.Do(func() {
		file_reflector_proto_rawDescData = protoimpl.X.CompressGZIP(file_reflector_proto_rawDescData)
	})
	return file_reflector_proto_rawDescData
}

var file_reflector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reflector_proto_goTypes = []interface{}{
	(*PointUpdate)(nil),        // 0: reflector.PointUpdate
	(*LapNumber)(nil),          // 1: reflector.LapNumber
	(*LapDuration)(nil),        // 2: reflector.LapDuration
	(*Response)(nil),           // 3: reflector.Response
	(*gps_go_proto.Point)(nil), // 4: gps.Point
	(*duration.Duration)(nil),  // 5: google.protobuf.Duration
}
var file_reflector_proto_depIdxs = []int32{
	4, // 0: reflector.PointUpdate.point:type_name -> gps.Point
	5, // 1: reflector.LapDuration.duration:type_name -> google.protobuf.Duration
	0, // 2: reflector.Reflect.ExportPoint:input_type -> reflector.PointUpdate
	1, // 3: reflector.Reflect.NewLap:input_type -> reflector.LapNumber
	2, // 4: reflector.Reflect.UpdateLapDuration:input_type -> reflector.LapDuration
	3, // 5: reflector.Reflect.ExportPoint:output_type -> reflector.Response
	3, // 6: reflector.Reflect.NewLap:output_type -> reflector.Response
	3, // 7: reflector.Reflect.UpdateLapDuration:output_type -> reflector.Response
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reflector_proto_init() }
func file_reflector_proto_init() {
	if File_reflector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reflector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reflector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LapNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reflector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LapDuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reflector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reflector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reflector_proto_goTypes,
		DependencyIndexes: file_reflector_proto_depIdxs,
		MessageInfos:      file_reflector_proto_msgTypes,
	}.Build()
	File_reflector_proto = out.File
	file_reflector_proto_rawDesc = nil
	file_reflector_proto_goTypes = nil
	file_reflector_proto_depIdxs = nil
}
