load("@rules_python//python:defs.bzl", "py_binary")

py_library(
  name = "tracks",
  srcs = ["__init__.py",
					"area27.py",
					"base.py",
					"oregon_raceway_park.py",
					"pacific_raceways.py",
					"portland_internal_raceways.py",
					"spokane_raceway.py",
					"test_track.py",
					"the_ridge.py",
					],
  visibility = ["//visibility:public"],
)
